name: Lint & type-check

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: ESLint
        run: npm run lint

      - name: TypeScript
        run: npx tsc --noEmit

      - name: actionlint
        uses: rhysd/actionlint@v1.7.7

      - uses: ./.github/actions/trigger-ci-failure
        if: failure() && github.actor != 'github-actions[bot]'
        with:
          gh-pat: ${{ secrets.GH_PAT }}
