name: Unit tests

on:
  pull_request:
  workflow_call:

concurrency:
  group: ${{ format('{0}-unit-test', github.event_name == 'pull_request' && github.ref || github.run_id) }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.detect.outputs.skip }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: ./.github/actions/detect-doc-only
        id: detect

  unit-test:
    needs: detect-changes
    if: needs.detect-changes.outputs.skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - uses: ./.github/actions/trigger-ci-failure
        if: failure() && github.actor != 'github-actions[bot]'
        with:
          gh-pat: ${{ secrets.GH_PAT }}
