name: Unit tests

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - uses: ./.github/actions/trigger-ci-failure
        if: failure() && github.actor != 'github-actions[bot]'
        with:
          gh-pat: ${{ secrets.GH_PAT }}
